/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FreelanceSiteService } from "../freelanceSite.service";
import { FreelanceSiteCreateInput } from "./FreelanceSiteCreateInput";
import { FreelanceSite } from "./FreelanceSite";
import { FreelanceSiteFindManyArgs } from "./FreelanceSiteFindManyArgs";
import { FreelanceSiteWhereUniqueInput } from "./FreelanceSiteWhereUniqueInput";
import { FreelanceSiteUpdateInput } from "./FreelanceSiteUpdateInput";
import { ProjectFindManyArgs } from "../../project/base/ProjectFindManyArgs";
import { Project } from "../../project/base/Project";
import { ProjectWhereUniqueInput } from "../../project/base/ProjectWhereUniqueInput";

export class FreelanceSiteControllerBase {
  constructor(protected readonly service: FreelanceSiteService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FreelanceSite })
  async createFreelanceSite(
    @common.Body() data: FreelanceSiteCreateInput
  ): Promise<FreelanceSite> {
    return await this.service.createFreelanceSite({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        url: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [FreelanceSite] })
  @ApiNestedQuery(FreelanceSiteFindManyArgs)
  async freelanceSites(
    @common.Req() request: Request
  ): Promise<FreelanceSite[]> {
    const args = plainToClass(FreelanceSiteFindManyArgs, request.query);
    return this.service.freelanceSites({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        url: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FreelanceSite })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async freelanceSite(
    @common.Param() params: FreelanceSiteWhereUniqueInput
  ): Promise<FreelanceSite | null> {
    const result = await this.service.freelanceSite({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        url: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FreelanceSite })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFreelanceSite(
    @common.Param() params: FreelanceSiteWhereUniqueInput,
    @common.Body() data: FreelanceSiteUpdateInput
  ): Promise<FreelanceSite | null> {
    try {
      return await this.service.updateFreelanceSite({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FreelanceSite })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFreelanceSite(
    @common.Param() params: FreelanceSiteWhereUniqueInput
  ): Promise<FreelanceSite | null> {
    try {
      return await this.service.deleteFreelanceSite({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/projects")
  @ApiNestedQuery(ProjectFindManyArgs)
  async findProjects(
    @common.Req() request: Request,
    @common.Param() params: FreelanceSiteWhereUniqueInput
  ): Promise<Project[]> {
    const query = plainToClass(ProjectFindManyArgs, request.query);
    const results = await this.service.findProjects(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        techStack: true,
        url: true,

        category: {
          select: {
            id: true,
          },
        },

        freelanceSite: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/projects")
  async connectProjects(
    @common.Param() params: FreelanceSiteWhereUniqueInput,
    @common.Body() body: ProjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      projects: {
        connect: body,
      },
    };
    await this.service.updateFreelanceSite({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/projects")
  async updateProjects(
    @common.Param() params: FreelanceSiteWhereUniqueInput,
    @common.Body() body: ProjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      projects: {
        set: body,
      },
    };
    await this.service.updateFreelanceSite({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/projects")
  async disconnectProjects(
    @common.Param() params: FreelanceSiteWhereUniqueInput,
    @common.Body() body: ProjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      projects: {
        disconnect: body,
      },
    };
    await this.service.updateFreelanceSite({
      where: params,
      data,
      select: { id: true },
    });
  }
}
